### ISSUE TITLE
GoveeApi is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nbear50** [jackdevey/Govee-CLI#2]
I cant get it to work
help please

**Comment by jackdevey** [comment]
Hi, Sorry for the late reply, I didn't seem to see this until now.

I'm working on a better version with a GUI in c# [here](https://github.com/jackdevey/govee-gui) which will make it much easier for users to use.

Until that is finished, however, ensure you have made a system environment variable `GOVEE_KEY` with the value of your API key and added the location of the exe file to the `Path` variable. If this doesn't help just let me know and I can prioritise finishing up the GUI for you.
